"""empty message

Revision ID: 6bbe148ff571
Revises: 823e0930f232
Create Date: 2022-05-07 00:55:23.866637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bbe148ff571'
down_revision = '823e0930f232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'wallet', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='unique')
    # ### end Alembic commands ###
